<?php
return [
    'checkbox' => 'checkbox',
    'color_picker' => 'color_picker',
    'cp' => 'input',
    'datalist' => 'datalist',
    'date' => 'date',
    'heure' => 'heure',
    'img' => 'file',
    'img_cropper' => 'img_cropper',
    'license' => 'input',
    'mail' => 'input',
    'mdp' => 'input',
    'mdp_2' => 'mdp_confirm',
    'multi_select' => 'multi_select',
    'nom' => 'input',
    'numb' => 'input',
    'numb_rue' => 'input',
    'pdf' => 'file',
    'rue' => 'input',
    'select' => 'select',
    'site' => 'input',
    'tel' => 'input',
    'text' => 'textarea',
    'titre' => 'input',
    'video' => 'file',
    'ville' => 'input',
];
